version: '3.1'

services:

  api:
    depends_on:
      - postgres
    build:
      context: .
    container_name: fastapi
    env_file: ./.env
    ports:
      - "8080:8080"
    command: bash -c "sleep 3 && create_tables && uvicorn api_test.api:app --host 0.0.0.0 --port 8080"

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    depends_on:
#      - postgres
#    ports:
#      - "8080:80"
#    env_file: ./.env
#    restart: unless-stopped
