---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/component: api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/component: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi
        app.kubernetes.io/component: api
    spec:
      initContainers:
      - name: create-tables
        image: ghcr.io/codeformuenster/mshack2020-counting-backend:master-9efb1b1
        command:
        - /bin/bash
        - -c
        args:
        - 'set -e && create_tables'
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-passwords
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: database-env-vars
              key: host
      containers:
      - name: fastapi
        image: ghcr.io/codeformuenster/mshack2020-counting-backend:master-9efb1b1
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-passwords
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: database-env-vars
              key: host
