apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mshack2020
commonLabels:
  app.kubernetes.io/part-of: counting-backend

resources:
- ./postgres.yaml
- ./counting-backend.yaml

configMapGenerator:
- name: database-env-vars
  behavior: create
  literals:
  - user=postgres
  - database=postgres
  - host=postgres

secretGenerator:
- name: database-passwords
  behavior: create
  envs:
  - ./secrets/database-passwords

images:
- name: ghcr.io/codeformuenster/mshack2020-counting-backend
  newTag: master-e7ccf97
